
# date format: 'YYYY-MM-DD'
start:
end:
path:
row:
latitude:
longitude:
output_path: None
satellite:
usgs_creds: C:\pymetric\usgs.txt
# pymetric directory structure: e.g. C:\pymetric\example\landsat\path\row\year
# mutually exclusive with output, put None if output is specified, and zipped: True
# make sure to leave output_path, satellite, path, row, latitude, and logitude empty
pymetric_root: C:\pymetric\example
clear_scenes: C:\pymetric\misc\clear_scenes.txt
return_list: False
zipped: True
max_cloud_percent: 100